### PR TITLE
Eliminate memory leak identified by Cppcheck.

### PR DESCRIPTION
**Pull request by MikeNeilson**
An initial change to some code to prevent identified memory leaks.

### CODE REVIEW

**Review by ktarbet — APPROVED** [review]

**Comment by MikeNeilson** [comment]
Probably good to have feedback from others.

My other thought was just convert this file to C++ and use std::unique_ptr to encapsulate the memory until released on assignment. the interface would still be C linkage so using programs wouldn't know. Would likely be cleaner but is a more drastic change and pulls in an additional library (libstdc++).

**Comment by ktarbet** [comment]
I'm not in favor of using C++ unless we had a larger strategy to introduce C++ into the whole code base in a bigger way.

**Review by perrymanmd — APPROVED** [review]
Oh no!, the forbidden `goto`! :)

**Review by jeffsuperglide — APPROVED** [review]

**Comment by MikeNeilson** [comment]
> Oh no!, the forbidden `goto`! :)

I challenge you to find a cleaner way to do that in plain C.

**Pull request merged**
