### PR TITLE
Fix: compilation in linux

### PR DESCRIPTION
**Pull request by Atreyagaurav**
I couldn't compile the hec-lib on Linux, so I have fixed some of the issues. These are minor changes that should not break anything but please do check compiling it on other platforms with this before merging.

### CODE REVIEW

**Comment by Atreyagaurav** [comment]
For more context:
The compilation failed with following error on Arch Linux for `strcasestr` function, so preventing it from being redefined:
```
src/Utilities/verticalDatum.c:43:13: error: conflicting types for ‘strcasestr’; have ‘const char *(const char *, const char *)’
   43 | const char* strcasestr(const char* haystack, const char* needle) {
      |             ^~~~~~~~~~
In file included from src/Utilities/verticalDatum.c:2:
/usr/include/string.h:380:14: note: previous declaration of ‘strcasestr’ with type ‘char *(const char *, const char *)’
  380 | extern char *strcasestr (const char *__haystack, const char *__needle)
      |              ^~~~~~~~~~
make[1]: *** [Makefile:35: Output/./src/Utilities/verticalDatum.c.o] Error 1
make[1]: Leaving directory '/home/.../hec-dss/heclib/heclib_c'
make: *** [Makefile:25: all] Error 2
```

**Comment by ktarbet** [comment]
Hi @Atreyagaurav ,   thanks for posting.

Do the tests all pass with your change on your OS?


Based on the error message, It might work to remove the const keyword in verticalDatum.c

from:
```c
const char* strcasestr(const char* haystack, const char* needle) 
```
to:
```c
char* strcasestr(const char* haystack, const char* needle) 
```

**Comment by ktarbet** [comment]
for the tests to work you will need to clone dss-test-data  

from the readme:

```bash
git clone https://github.com/HydrologicEngineeringCenter/hec-dss.git
cd hec-dss
rm -fr ./dss-test-data
git clone https://github.com/HydrologicEngineeringCenter/dss-test-data.git
In the hec-dss/heclib directory, execute make clean ; make
In the hec-dss/test/C directory, execute ./unix_test
In the hec-dss/test/Dss-C directory, execute make clean ; make test
In the hec-dss/test/Fortran directory, execute make clean ; make test

**Comment by Atreyagaurav** [comment]
Thank you. 

I ran the tests with my patch and all of them failed. I couldn't test without the `strcasestr` patch because it just won't compile, but I think the test errors don't seem to be from it as all of them have `*** stack smashing detected ***: terminated` in it.

## `./unix_test` in `hec-dss/test/C`
```
os = Linux
../../heclib//Output/heclib.a
-m64 -c -fPIC -g -std=gnu99 -I../../heclib/heclib_c/src/headers
endian.c
running endian

your system is: Little endian

Data types and sizes
int        4
int*       8
float      4
float*     8
long       8
long long  8
long long* 8
void*      8
char       1
char*      8
ts_readv6.c
running ts_readv6
*** stack smashing detected ***: terminated
unix_test: line 34: 51674 Aborted                 (core dumped) ./Output/$1 $2 > ./Output/$1_test.log
Test_Error with ts_readv6
ts_write_irregular.c
running ts_write_irregular
ExampleSecondGranularity.c
running ExampleSecondGranularity
SampleText1.c
running SampleText1
SamplePairedData.c
running SamplePairedData
ExampleMinuteGranularity.c
running ExampleMinuteGranularity
ts_write.c
running ts_write
ExampleTimeSeries1.c
running ExampleTimeSeries1
ExampleTimeSeries2.c
running ExampleTimeSeries2
GridTest.c
running GridTest
GridTest.dss: data
GridTest.c
running GridTest
zopenExample.c
running zopenExample

=============
Native Test Summary 
============ 
C test program run is finished
13 tests found
12 tests successful
1 tests failed 
Failed 
```

The `ts_readv6_test.log` file is empty.

## `test/Dss-C`
```
Data as doubles:
	 0: 09Aug2018 0800	100.000000
	 1: 09Aug2018 1600	200.000000
	 2: 10Aug2018 0000	300.000000
	 3: 10Aug2018 0800	400.000000
	 4: 10Aug2018 1600	500.000000
	 5: 11Aug2018 0000	600.000000
	 6: 11Aug2018 0800	700.000000
	 7: 11Aug2018 1600	800.000000

test zinquire return value for FVER

test Jira DSS-163 weekly time series issue

test copy large record
    -----DSS---ZOPEN:  New File Opened,  File: large-record-dst6.dss
                       Unit:    6;  DSS Version: 6-YO  Library 7-IS
    -----DSS---ZOPEN:  New File Opened,  File: large-record-dst6.dss
                       Unit:    6;  DSS Version: 6-YO  Library 7-IS

test miscellaneous stuff

test grid memory

test units issue 126
    -----DSS---ZOPEN:  New File Opened,  File: units_issue_126.dss
                       Unit:    3;  DSS Version: 6-YO  Library 7-IS
*** stack smashing detected ***: terminated
make: *** [Makefile:50: test] Error 134
```

## `hec-dss/test/Fortran`
```
......................
8926 paried data tests passed


*** Enter DssCodeTest7 ***
 Begin testOpen
 testOpen Passed successfully
  
 Start Run Tests
 Begin testWrite
Basic zwrite Passed Successfully
 Begin test_RTS_Basic
*** stack smashing detected ***: terminated

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7b60d8b5d1cf in ???
#1  0x7b60d8bb63f4 in ???
#2  0x7b60d8b5d11f in ???
#3  0x7b60d8b444c2 in ???
#4  0x7b60d8b45353 in ???
#5  0x7b60d8c45798 in ???
#6  0x7b60d8c46a53 in ???
#7  0x5fa255464319 in zrrts_
	at src/DssInterface/v6and7/zrrts.f:44
#8  0x5fa255389ca7 in test_rts_basic_
	at source/test_RTS_Basic.f90:47
#9  0x5fa2553a0f34 in test_rts_main_
	at source/test_RTS_Main.f90:41
#10  0x5fa255349a87 in runtests_
	at source/runTests.f90:30
#11  0x5fa2553486cc in dsscodetest7_
	at source/DssCodeTest7.f90:93
#12  0x5fa2553df82d in testdss7
	at source/TestDss7.f90:39
#13  0x5fa2553df877 in main
	at source/TestDss7.f90:43
make: *** [Makefile:48: test] Error 134
```

**Comment by ktarbet** [comment]
Thanks for running the tests!

What version of gfortran and gcc is your system using?   I have see issues with the latest compilers and the latest Rocky Linux, which is causing motivation for dropping the Fortran dependencies from HEC-DSS.

**Comment by Atreyagaurav** [comment]
Here are the versions:

gcc (GCC) 14.2.1 20240910
GNU Fortran (GCC) 14.2.1 20240910

From what I could find, the cause seems to be due to a memory bug that triggers a safety mechanism (https://stackoverflow.com/a/1347464/11825320).

**Comment by ktarbet** [comment]
Thanks.  Your compilers are newer than what we use for builds.  Some of memory 'tricks' the old Fortran code is using could be the issue.

If you need to run HEC-DSS on your specific version of linux; depending on your needs, please consider trying a pre-compiled version.

A longer term project -next two years is to remove the Fortran calls from DSS and only have DSS version 7 support in the code.

**Comment by Atreyagaurav** [comment]
Yeah.

Compiling it is not a problem, only the test from `v6` file, so I think it should be fine to use the library as long as I only use v7 files (which I do).

The reason I started compiling it was because the pre-compiled versions didn't work for me before. I tested again just now and I got errors.


For example, when I try to use the `heclib.a` that is available to download from here: https://www.hec.usace.army.mil/confluence/dssdocs/dsscprogrammer/release-notes (Note: [The zip file here] (https://www.hec.usace.army.mil/nexus/#browse/search/maven=attributes.maven2.artifactId%3Dheclib%20AND%20version%3D7-IU-4*:NX.coreui.model.Component-1:a81fe9f475e8d3b9c18b59bd8a0f2892) only has `heclib.a` not `heclib.so` for C programmers.)

I get errors from using that `heclib.a` if I try to compile my program.
```
/usr/bin/ld: /tmp/ccZ8bzDH.o: in function `extract_timeseries':
dss2csv.c:(.text+0x33a): undefined reference to `zstructTsNew'
/usr/bin/ld: dss2csv.c:(.text+0x367): undefined reference to `ztsRetrieve'
/usr/bin/ld: dss2csv.c:(.text+0x428): undefined reference to `getDateAndTime'
/usr/bin/ld: dss2csv.c:(.text+0x452): undefined reference to `zisMissingFloat'
/usr/bin/ld: /tmp/ccZ8bzDH.o: in function `extract_grid':
dss2csv.c:(.text+0x63f): undefined reference to `zstructSpatialGridNew'
/usr/bin/ld: dss2csv.c:(.text+0x664): undefined reference to `zspatialGridRetrieve'
/usr/bin/ld: dss2csv.c:(.text+0xc83): undefined reference to `zstructFree'
/usr/bin/ld: /tmp/ccZ8bzDH.o: in function `main':
dss2csv.c:(.text+0xd79): undefined reference to `zsetMessageLevel'
/usr/bin/ld: dss2csv.c:(.text+0xda2): undefined reference to `zfileName'
/usr/bin/ld: dss2csv.c:(.text+0xdf2): undefined reference to `hec_dss_zopen'
/usr/bin/ld: dss2csv.c:(.text+0xe16): undefined reference to `zstructCatalogNew'
/usr/bin/ld: dss2csv.c:(.text+0xe3f): undefined reference to `zcatalog'
/usr/bin/ld: dss2csv.c:(.text+0x104b): undefined reference to `zstructFree'
/usr/bin/ld: dss2csv.c:(.text+0x105a): undefined reference to `zclose'
```
Which happens even if I compile this program myself. So to use `.so` file instead of `.a` I had to compile it myself.

And because the prebuilt `.a` file has this error, I haven't had success with other language bindings (python, R, etc) in linux as well. So, I'm just compiling it myself to fix any issues so I can make tools using hecdss.

Here is the CLI tool I made using it if you want to test the compilation: https://github.com/Atreyagaurav/dss2csv

**Comment by ktarbet** [comment]
Thanks for sharing your tool;  That looks nice!

Longer term beyond dropping the Fortran and DSS version 6 support.  We have a new DSS 7 only API with  [hecdss](https://github.com/HydrologicEngineeringCenter/hec-dss/tree/master/heclib/hecdss).  On top of hecdss.dll we have python and .net bindings so far, java may follow.  These bindings add a layer to hide DSS deeper to support future implementations of the internals of DSS.


https://github.com/HydrologicEngineeringCenter/hec-dss-python
https://github.com/HydrologicEngineeringCenter/hec-dss-dotnet

**Comment by Atreyagaurav** [comment]
Thank you. The python library seems to be a new from the one I found and couldn't use years ago. That might make things a lot easier than trying to write C converters.

Hope HEC will keep everything open source.

**Pull request closed without merging**
